Be nice to users and give them a very friendly requirements script.

diff --git a/net/zircon/pkg/+REQ_B b/net/zircon/pkg/+REQ_B
--- a/net/zircon/pkg/+REQ_B
+++ b/net/zircon/pkg/+REQ_B
@@ -1,8 +1,30 @@
-#!/bin/sh
-if [ ! -f /usr/local/bin/dpwish ]; then
-	echo "This package requires that dpwish from the tcl-dp package"
-	echo "be installed in /usr/local/bin.  Install the tcl-dp package"
-	echo "first before trying to install the binary package of zircon."
-	exit 1
+if pkg_info -e tcl-dp_bin; then
+	exit 0;
+else
+	echo > /dev/tty
+	echo "Error:  This package will not work without tcl-dp_bin installed first." >/dev/tty
+	if [ -f tcl-dp_bin.tgz ]; then
+		echo -n "I see a tcl-dp_bin release here.  Would you like me to install it now? [yes] "
+		read ans
+		case "$ans" in
+			[Nn]*)
+				echo "Ok, please do it by hand and install this package again." > /dev/tty
+				exit 1;
+			;;
+			[Yy]*|*)
+				if pkg_add tcl-dp_bin.tgz ; then
+					echo "Sorry, the pkg_add of tcl-dp_bin.tgz failed!  Please do it by hand." > /dev/tty
+					exit 1;
+				else
+					echo "tcl-dp_bin added successfully!  Proceeding with gic." > /dev/tty
+					exit 0;
+				fi
+			;;
+		esac
+	else
+		echo "Please install package tcl-dp_bin before trying to install this package" > /dev/tty
+		exit 1;
+	fi
+	echo > /dev/tty
 fi
-exit 0
+
