Initial import of version 0.79. This is not current, 0.81 is, but the last version that compiles with gcc-2.4.5.

diff --git a/math/octave/octave/configure.in b/math/octave/octave/configure.in
--- a/math/octave/octave/configure.in
+++ b/math/octave/octave/configure.in
@@ -77,12 +77,17 @@ fi
 
 AC_PROG_CC
 AC_GCC_TRADITIONAL
+AC_MINIX
+AC_ISC_POSIX
 AC_AIX
+AC_DYNIX_SEQ
+AC_ALLOCA
+AC_CONST
 
 # Do special things for gcc.
 
 case "$CC" in
-  gcc*)
+  gcc* | */gcc*)
     CFLAGS="-g -O -Wall"
     LDFLAGS="-g -O"
     gcc_version=`gcc -v 2>&1 | grep "^gcc version" | sed 's/^gcc version *//'`
@@ -96,6 +101,11 @@ EOF
     esac
     ;;
   *)
+    cat << EOF
+warning: found environment variable CC = \`$CC'.  If this is not a
+         derivative of GCC, you should probably consider using GCC
+         version 2.x instead.
+EOF
     CFLAGS="-g"
     LDFLAGS="-g"
     ;;
@@ -103,8 +113,8 @@ esac
 AC_SUBST(CFLAGS)dnl
 AC_SUBST(LDFLAGS)dnl
 
-AC_PROGRAM_CHECK(GXX, g++, g++, [])dnl
-if test "$GXX" = g++ ; then
+AC_PROGRAM_CHECK(CXX, g++, g++, [])dnl
+if test "$CXX" = g++ ; then
   CXXFLAGS="-g -O -Wall"
   gxx_version=`g++ -v 2>&1 | grep "^g.. version" | sed 's/^g.. version *//'`
   case "$gxx_version" in
@@ -220,8 +230,23 @@ AC_SUBST(DEFAULT_DOT_O_FROM_DOT_F)dnl
 AC_PROG_INSTALL
 AC_PROG_RANLIB
 AC_STDC_HEADERS
+AC_HAVE_HEADERS(string.h varargs.h)
+AC_HAVE_HEADERS(sys/time.h sys/fcntl.h sys/ttold.h sys/ptem.h)
 AC_UNISTD_H
 AC_DIR_HEADER
+AC_HAVE_FUNCS(setvbuf getcwd bzero rindex vfprintf vsprintf)
+AC_STRUCT_TM
+AC_SETVBUF_REVERSED
+TERMLIBS=""
+for termlib in termcap terminfo curses termlib ; do
+  AC_HAVE_LIBRARY(${termlib}, [TERMLIBS="${TERMLIBS} -l${termlib}"])
+  case "${TERMLIBS}" in
+    *-l${termlib}*)
+      break
+    ;;
+  esac
+done
+AC_SUBST(TERMLIBS)
 
 # For now, don't define LEXLIB to be -lfl -- we don't use anything in
 # it, and it might not be installed.
@@ -269,22 +294,22 @@ case "$RETSIGTYPE" in
 esac
 AC_SUBST(VOID_SIGHANDLER)dnl
 
-AC_HAVE_HEADERS(termio.h)dnl
+AC_HEADER_CHECK(termios.h, DEFS="$DEFS -DHAVE_TERMIOS_H=1",
+  AC_HEADER_CHECK(termio.h, DEFS="$DEFS -DHAVE_TERMIO_H=1",
+    AC_HEADER_CHECK(sgtty.h, DEFS="$DEFS -DHAVE_SGTTY_H=1", [])))dnl
 case "$DEFS" in
-  *HAVE_TERMIO_H*)
+  *HAVE_TERMIOS_H* | *HAVE_TERMIO_H* | *HAVE_SGTTY_H*)
   ;;
   *)
-    AC_HAVE_HEADERS(sgtty.h)dnl
-    case "$DEFS" in
-      *HAVE_SGTTY_H*)
-      ;;
-      *)
-        echo "I couldn't find either termio.h or sgtty.h!"
-        exit 1
-        ;;
-    esac
-    ;;
+    cat << EOF
+error: I couldn't find termios.h, termio.h, or sgtty.h, and I can't
+       continue without them.  To compile Octave, your system must
+       have at least one of these header files.
+EOF
+    exit 1
+  ;;
 esac
+
 
 # Hack for readline's sysdep.h
 
@@ -302,11 +327,9 @@ esac
 # are often available.  If they are missing, we try to replace them
 # with functions from the BSD/NET2 math library.
 
-XLIBS="$LIBS"
-LIBS="$XLIBS -lm"
+AC_HAVE_LIBRARY(-lm)dnl
 AC_HAVE_FUNCS(finite isnan isinf)dnl
 AC_REPLACE_FUNCS(acosh asinh atanh)dnl
-LIBS="$XLIBS"
 
 if test -n "$LIBOBJS"; then
   for func in $LIBOBJS
@@ -371,20 +394,12 @@ warning: I didn't find gnuplot.  It isn't necessary to have gnuplot
 EOF
 fi
 
-AC_PROGRAM_CHECK(DEFAULT_PAGER, less, less, [])dnl
-if test -z "$DEFAULT_PAGER"; then
-  AC_PROGRAM_CHECK(DEFAULT_PAGER, more, more, [])dnl
-fi
-if test -z "$DEFAULT_PAGER"; then
-  AC_PROGRAM_CHECK(DEFAULT_PAGER, page, page, [])dnl
-fi
-if test -z "$DEFAULT_PAGER"; then
-  AC_PROGRAM_CHECK(DEFAULT_PAGER, pg, pg, [])dnl
-fi
+AC_PROGRAMS_CHECK(DEFAULT_PAGER, less more page pg, [])dnl
 if test -z "$DEFAULT_PAGER"; then
   echo "warning: I couldn't find less(1), more(1), page(1), or pg(1)"
+elif test "$DEFAULT_PAGER" = less; then
+  DEFAULT_PAGER="less -e"
 fi
-AC_SUBST(DEFAULT_PAGER)dnl
 
 AC_PROGRAM_CHECK(RUNTEST, runtest, runtest, [])dnl
 AC_PROGRAM_CHECK(EXPECT, expect, expect, [])dnl
@@ -393,20 +408,19 @@ if test -z "$EXPECT" ; then
 fi
 AC_SUBST(RUNTEST)dnl
 
-define([tmpa], [libcruft/blas/Makefile libcruft/dassl/Makefile])dnl
-define([tmpb], [libcruft/fftpack/Makefile])dnl
-define([tmpc], [libcruft/fsqp/Makefile libcruft/lapack/Makefile])dnl
-define([tmpd], [libcruft/linpack/Makefile libcruft/minpack/Makefile])dnl
-define([tmpe], [libcruft/misc/Makefile libcruft/npsol/Makefile])dnl
-define([tmpf], [libcruft/odepack/Makefile libcruft/qpsol/Makefile])dnl
-define([tmpg], [libcruft/quadpack/Makefile libcruft/ranlib/Makefile])dnl
-define([tmph], [libcruft/villad/Makefile])dnl 
+define([tmpa], [libcruft/blas/Makefile libcruft/balgen/Makefile])dnl
+define([tmpb], [libcruft/dassl/Makefile libcruft/eispack/Makefile])dnl
+define([tmpc], [libcruft/fftpack/Makefile libcruft/fsqp/Makefile])dnl
+define([tmpd], [libcruft/lapack/Makefile libcruft/linpack/Makefile])dnl
+define([tmpe], [libcruft/minpack/Makefile libcruft/misc/Makefile])dnl
+define([tmpf], [libcruft/npsol/Makefile libcruft/odepack/Makefile])dnl
+define([tmpg], [libcruft/qpsol/Makefile libcruft/quadpack/Makefile])dnl
+define([tmph], [libcruft/ranlib/Makefile libcruft/villad/Makefile])dnl 
 define([cruftdirs], [tmpa tmpb tmpc tmpd tmpe tmpf tmpg tmph])dnl
 define([tmpA], [Makefile Makeconf libcruft/Makefile libcruft/Makerules])dnl
-define([tmpB], [liboctave/Makefile src/Makefile])dnl
-define([tmpC], [dld/Makefile readline/Makefile readline/doc/Makefile])dnl
+define([tmpB], [liboctave/Makefile src/Makefile dld/Makefile])dnl
+define([tmpC], [info/Makefile readline/Makefile readline/doc/Makefile])dnl
 define([tmpD], [readline/examples/Makefile doc/Makefile])dnl
 define([tmpE], [scripts/Makefile test/Makefile])dnl
-define([tmpF], [test/config/Makefile test/octave/Makefile])dnl
-define([srcdirs], [tmpA tmpB tmpC tmpD tmpE tmpF])dnl
+define([srcdirs], [tmpA tmpB tmpC tmpD tmpE])dnl
 AC_OUTPUT([srcdirs cruftdirs])dnl
